import Vehicles from './Vehicles';

export { default as Ecommerce } from './Home';
export { default as Kanban } from './Kanban';
export { default as ServiceRecords } from './ServiceRecords';
export { default as ServiceRecordDetails } from './ServiceRecordDetails';
export { default as Employees } from './Employees';
export { default as Editor } from './Editor';
export { default as Customers } from './Customers';
export { default as ColorPicker } from './colorPicker';
export { default as Calendar } from './calendar';
export { default as Area } from './Charts/Area';
export { default as Bar } from './Charts/Bar';
export { default as ColorMapping } from './Charts/ColorMapping';
export { default as Financial } from './Charts/Financial';
export { default as Line } from './Charts/Line';
export { default as Pie } from './Charts/Pie';
export { default as Pyramid } from './Charts/Pyramid';
export { default as Stacked } from './Charts/Stacked';
export {default as Home} from './Home';
export { default as Vehicles } from './Vehicles';
export {default as Invoices} from './Invoices';
export {default as Payments} from './Payments';