# Generated by Django 5.1.5 on 2025-01-25 09:59

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz1234567890', length=8, max_length=25, prefix='', primary_key=True, serialize=False, unique=True)),
                ('make', models.CharField(default='Toyota', help_text='Vehicle make (e.g., Toyota)', max_length=50)),
                ('model', models.CharField(help_text='Vehicle model (e.g., Corolla)', max_length=50)),
                ('year', models.PositiveIntegerField(help_text='Year of manufacture')),
                ('registration_number', models.CharField(blank=True, help_text='Registration number (optional)', max_length=20, null=True, unique=True)),
                ('color', models.CharField(blank=True, help_text='Vehicle color (optional)', max_length=20, null=True)),
                ('vin', models.CharField(blank=True, help_text='Vehicle Identification Number (optional)', max_length=17, null=True, unique=True)),
                ('status', models.CharField(choices=[('Waiting for Service', 'Waiting for Service'), ('Next Job', 'Next Job'), ('Being Serviced', 'Being Serviced'), ('Job Stoppage', 'Job Stoppage'), ('Waiting for Approval', 'Waiting for Approval'), ('Waiting for Parts', 'Waiting for Parts'), ('Waiting for Settlement', 'Waiting for Settlement'), ('Waiting for Car Wash', 'Waiting for Car Wash'), ('Waiting for Invoicing', 'Waiting for Invoicing')], default='Active', help_text='Current status of the vehicle')),
                ('queue_position', models.PositiveIntegerField(blank=True, help_text='Position in the queue (if applicable)', null=True)),
                ('owner', models.ForeignKey(help_text='The owner of the vehicle', on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
