# Generated by Django 5.1.2 on 2024-11-03 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(default='Toyota', max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('registration_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('vin', models.CharField(blank=True, max_length=17, null=True, unique=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('In Service', 'In Service'), ('Completed', 'Completed')], default='Active', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
