# Generated by Django 4.2.17 on 2025-01-05 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobQueue',
            fields=[
                ('queue_id', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz1234567890', length=8, max_length=25, prefix='', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Name of the queue', max_length=50)),
                ('description', models.CharField(blank=True, help_text='Description of the queue', max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the queue was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the queue was last updated')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz1234567890', length=8, max_length=25, prefix='', primary_key=True, serialize=False, unique=True)),
                ('make', models.CharField(default='Toyota', help_text='Vehicle make (e.g., Toyota)', max_length=50)),
                ('model', models.CharField(help_text='Vehicle model (e.g., Corolla)', max_length=50)),
                ('year', models.PositiveIntegerField(help_text='Year of manufacture')),
                ('registration_number', models.CharField(blank=True, help_text='Registration number (optional)', max_length=20, null=True, unique=True)),
                ('color', models.CharField(blank=True, help_text='Vehicle color (optional)', max_length=20, null=True)),
                ('vin', models.CharField(blank=True, help_text='Vehicle Identification Number (optional)', max_length=17, null=True, unique=True)),
                ('status', models.CharField(choices=[('Waiting for Service', 'Waiting for Service'), ('Next Job', 'Next Job'), ('Being Serviced', 'Being Serviced'), ('Job Stoppage', 'Job Stoppage'), ('Waiting for Approval', 'Waiting for Approval'), ('Waiting for Parts', 'Waiting for Parts'), ('Waiting for Settlement', 'Waiting for Settlement'), ('Waiting for Car Wash', 'Waiting for Car Wash'), ('Waiting for Invoicing', 'Waiting for Invoicing')], default='Active', help_text='Current status of the vehicle')),
                ('queue_position', models.PositiveIntegerField(blank=True, help_text='Position in the queue (if applicable)', null=True)),
                ('owner', models.ForeignKey(default='N/A', help_text='The owner of the vehicle', on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QueueVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, help_text='Position of the vehicle in the queue')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_portal.jobqueue')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_portal.vehicle')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('vehicle', 'queue')},
            },
        ),
        migrations.AddField(
            model_name='jobqueue',
            name='vehicles',
            field=models.ManyToManyField(help_text='Vehicles in this queue', related_name='vehicle_queue', through='employee_portal.QueueVehicle', to='employee_portal.vehicle'),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz1234567890', length=8, max_length=25, prefix='', primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', help_text='Current status of the job', max_length=20)),
                ('priority', models.PositiveIntegerField(default=1, help_text='Priority of the job (higher is more urgent)')),
                ('deadline', models.DateTimeField(blank=True, help_text='Deadline for completing the job', null=True)),
                ('comments', models.TextField(blank=True, help_text='Additional comments about the job', null=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Employee assigned to this job', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_assignee', to=settings.AUTH_USER_MODEL)),
                ('queue', models.ForeignKey(blank=True, help_text='Queue associated with this job', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue', to='employee_portal.jobqueue')),
                ('vehicle', models.ForeignKey(help_text='Vehicle associated with this job', on_delete=django.db.models.deletion.CASCADE, related_name='job_vehicles', to='employee_portal.vehicle')),
            ],
        ),
    ]
