# Generated by Django 4.2.17 on 2025-01-05 03:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='When the job was created'),
            preserve_default=False,
        ),
    ]
